.github/workflows/tests.yml
Formula/cosign.rb
README.md

the CI for linux is not working properly, will need a bit more time to investigate, but the focus was for MacOS users and that is passing :)
will do the Linux in a follow up after perform tests in the mac and in a Linux box as well

Add initial homebrew cosign

---

.github/workflows/tests.yml
Formula/cosign.rb

update tap to use cosign 1.0.0

update tap to use cosign 1.0.0

---

Formula/rekor-cli.rb
README.md

Add rekor-cli to be installed with homebrew 😄

add rekor-cli to homebrew tap

---

Formula/cosign.rb

cosign: update to release v1.3.0
```release-note
cosign: update to release v1.3.0
```

cosign: update to release v1.3.0

---

Formula/sget.rb
README.md

add sget to homebrew
n/a
```release-note
add sget to homebrew
```

add sget to homebrew

---

Formula/cosign.rb

cosign: update to cosign 1.4.0 release
n/a
```release-note
cosign: update to cosign 1.4.0 release
```

cosign: update to cosign 1.4.0 release

---

Formula/cosign.rb

- update cosign to v1.4.1
n/a
```release-note
update cosign to v1.4.1
```

update cosign to v1.4.1

---

Formula/sget.rb

- update sget to v1.4.1
n/a
```release-note
update sget to v1.4.1
```

update sget to v1.4.1

---

Formula/rekor-cli.rb

- update rekor-cli brew to v0.4.0
n/a
```release-note
update rekor-cli brew to v0.4.0
```

update rekor-cli brew to v0.4.0

---

Formula/cosign.rb

Signed-off-by: Bob Callaway <bob.callaway@gmail.com>

update cosign to v1.5.0

---

Formula/cosign.rb

- update cosign to 1.5.1
n/a
```release-note
update cosign to 1.5.1
```

update cosign to 1.5.1

---

Formula/sget.rb

- update sget to 1.5.1
n/a
```release-note
update sget to 1.5.1
```

update sget to 1.5.1

---

Formula/rekor-cli.rb

update rekor-cli to release v0.5.0
n/a
```release-note
update rekor-cli to release v0.5.0
```

update rekor-cli to release v0.5.0

---

Formula/cosign.rb
Formula/sget.rb

Signed-off-by: Bob Callaway <bob.callaway@gmail.com>

update to v1.5.2

---

Formula/cosign.rb
Formula/sget.rb

update formulas to use release v1.6.0 for
- cosign
- sget
n/a
```release-note
update formulas to use release v1.6.0
```

update formulas to use release v1.6.0

---

.github/dependabot.yml
.github/workflows/tests.yml

- use git hash in the actions and add dependabot config
n/a
```release-note
NONE
```

use git hash in the actions and add dependabot config

---

Formula/sget.rb

- update sget formula to release v1.7.1

update sget formula to release v1.7.1

---

Formula/cosign.rb

- update cosign formula to release v1.7.1

update cosign formula to release v1.7.1

---

Formula/sget.rb

- update sget formula to release v1.7.2
n/a
```release-note
NONE
```

update sget formula to release v1.7.2

---

Formula/rekor-cli.rb

- update rekor-cli to 0.6.0
n/a
```release-note
NONE
```

update rekor-cli to 0.6.0

---

Formula/sget.rb

- update sget to 1.8.0
n/a
```release-note
NONE
```

update sget to 1.8.0

---

Formula/cosign.rb

- update cosign to 1.8.0
n/a
```release-note
NONE
```

update cosign to 1.8.0

---

Formula/gitsign.rb
README.md

- add gitsign to homebrew
Fixes https://github.com/sigstore/gitsign/issues/61
```release-note
add gitsign to homebrew
```

add gitsign to homebrew

---

Formula/rekor-cli.rb

- update rekor formula to use release 0.7.0
n/a
```release-note
NONE
```

update rekor formula to use release 0.7.0

---

Formula/cosign.rb

- update cosign to 1.9.0
n/a 
```release-note
NONE
```

update cosign to 1.9.0

---

Formula/sget.rb

- update sget to 1.9.0
n/a
```release-note
NONE
```

update sget to 1.9.0

---

Formula/rekor-cli.rb

- update formula to use rekor release v0.8.1
n/a

update formula to use rekor release v0.8.1

---

Formula/rekor-cli.rb

- update rekor formula to use release 0.8.2

update rekor formula to use release 0.8.2

---

Formula/rekor-cli.rb

update rekor to v0.9.0

---

Formula/sget.rb

- update sget to use release v1.10.0
`n/a`
`n/a`

update sget to use release v1.10.0

---

Formula/rekor-cli.rb

- upgrade rekor-cli to use release v0.10.0

upgrade rekor-cli to use release v0.10.0

---

Formula/sget.rb

update sget to v1.10.1

---

Formula/cosign.rb

update cosign to v1.10.1

---

Formula/cosign.rb

update cosign to v1.11.0

---

Formula/sget.rb

update sget to v1.11.0

---

Formula/rekor-cli.rb

update rekor-cli to v0.11.0

---

Formula/sget.rb

bump sget to v1.11.1

---

Formula/cosign.rb

bump cosign to v1.11.1

---

Formula/gitsign-credential-cache.rb
Formula/gitsign.rb

Update to gitsign v0.3.0 - https://github.com/sigstore/gitsign/releases/tag/v0.3.0

gitsign v0.3.0

---

Formula/rekor-cli.rb

update rekor-cli to v0.12.0

---

Formula/cosign.rb

bump cosign to v1.12.0

---

Formula/sget.rb

bump sget to v1.12.0

---

Formula/rekor-cli.rb

bump rekor-cli to v0.12.1

---

Formula/cosign.rb

bump cosign to v1.12.1

---

Formula/gitsign-credential-cache.rb
Formula/gitsign.rb

Update gitsign 0.3.1 - https://github.com/sigstore/gitsign/releases/tag/v0.3.1
Update gitsign 0.3.1 - https://github.com/sigstore/gitsign/releases/tag/v0.3.1

Update gitsign 0.3.1

---

Formula/rekor-cli.rb

update rekor-cli to v0.12.2

---

Formula/cosign.rb

bump cosign to v1.13.0

---

Formula/sget.rb

bump sget to v1.13.0

---

Formula/policy-tester.rb
README.md

See https://github.com/sigstore/policy-controller/tree/main/examples

Add new formula for policy-tester CLI

---

Formula/policy-tester.rb

- fix darwin/linux arm64 sha256sum
followup of #79 
cc @jdolitsky

fix darwin/linux arm64 sha256sum

---

Formula/gitsign-credential-cache.rb
Formula/gitsign.rb

Update gitsign to v0.4.1
Update gitsign to v0.4.1
Website update TODO in another PR.

Update gitsign v0.4.1

---

.github/workflows/auto-merge.yml

- add enable auto-merge for dependabot PRs
related: https://github.com/sigstore/community/issues/202

add enable auto-merge for dependabot PRs

---

Formula/gitsign-credential-cache.rb
Formula/gitsign.rb

Bumps Gitsign taps to [v0.5.2](https://github.com/sigstore/gitsign/releases/tag/v0.5.2)
NONE

Gitsign v0.5.2

---

Formula/cosign.rb

cosign v2.0.0

---

Formula/policy-tester.rb

Bump policytester to v0.7.0
SHAs are from here:
https://github.com/sigstore/policy-controller/releases/download/v0.7.0/policy-controller_checksums.txt
And just copied here for clarity:
```
1f8b43b4947faaeab920f3c39364b5b55c2c7b2bf41d41b8a6dfffcc2b89a3b6  tester-windows-amd64.exe
311060cc7e9f139b29487497926aba216c1272bb19e29e9c555b44b4c7fec841  tester-linux-arm
3c8dd03c7da5e6c6e506c061a958c26cb199c5d2bb95216a887dd8645e1941d6  tester-darwin-amd64
440bb9b4024372a2a6a3b970ed554eb3de5d234a8114fbe7504cc195d4c29fa0  tester-linux-s390x
50cbc03181ccac4392da4f6651d5bc93795cf8ec61b1d7953e1a875061623efe  tester-linux-arm64
51b8c988f930464de021fa73cbba584db592be2d9cbbd5f4d49ce20578260251  tester-linux-ppc64le
e67ca887c5df0c6d78a67b45f0adc6b9fc8dd43e1f12a0fbbe45977ee243fe78  tester-linux-amd64 …
```

bump policy-tester to v0.7.0.

---

Formula/rekor-cli.rb

bump rekor-cli to v1.1.0

---

Formula/cosign.rb

update Formula for cosign v2.0.2

---

Formula/rekor-cli.rb

- bump rekor-cli to release v1.1.1

bump rekor-cli to release v1.1.1

---

Formula/cosign.rb

bump cosign to v2.1.0

---

Formula/cosign.rb

bump cosign to v2.1.1

---

Formula/rekor-cli.rb

bump rekor-cli to v1.2.2

---

Formula/gitsign-credential-cache.rb
Formula/gitsign.rb

gitsign: Bump to v0.7.1
Updated gitsign to v0.7.1

gitsign: Bump to v0.7.1

---

Formula/cosign.rb

bump cosign to v2.2.0

---

Formula/rekor-cli.rb

bump rekor-cli to v1.3.0

---

Formula/cosign.rb

bump cosign to v2.2.1

---

Formula/rekor-cli.rb

bump rekor-cli to v1.3.3

---

Formula/gitsign-credential-cache.rb
Formula/gitsign.rb

Bump gitsign to v0.8.0
* Bump gitsign to v0.8.0

Bump gitsign to v0.8.0

---

Formula/rekor-cli.rb

bump rekor-cli for v1.3.4

---

Formula/cosign.rb

update cosign to v2.2.3

---

Formula/cosign.rb

update cosign to v2.2.4

---

Formula/cosign.rb

bump cosign tap to v2.4.1

---

Formula/cosign.rb

bump for cosign v2.4.2 release
